---
title: "RWorksheet_Bajacan#4b"
author: "Gilbert Bajacan"
output: pdf_document
date: "2023-11-08"
---

``` {r num1}

vectorA <- c(1, 2, 3, 4, 5)
matrixA <- matrix(0, nrow = 5, ncol = 5)

for (i in 1:5) {
  for (j in 1:5) {
    matrixA[i, j] <- abs(vectorA[i] - vectorA[j])
  }
}
matrixA
```

``` {r num2}
n <- 5  # The number of rows

for (i in 1:n) {
  for (j in 1:i) {
    cat("*")
  }
  cat("\n")
}
```
``` {r num3}
start <- as.numeric(readline("Enter the starting number: "))
a <- 0
b <- 1
cat("Starting from", start, "up to 500:\n")
repeat {
  if (a >= start) {
    cat(a, " ")
  }
  c <- a + b
  a <- b
  b <- c

  if (a > 500) {
    break
  }
}
```
``` {r num4 A}
table <- read.table(file = "shoesize.csv", header = TRUE, sep = ',')
table
```


``` {r  A}
head(table, n = 6)
```


``` {r num4 B}
male_subset <- subset(table, Gender == "M")
female_subset <- subset(table, Gender == "F")
male_count <- nrow(male_subset)
female_count <- nrow(female_subset)
cat("Number of Male observations:", male_count, "\n")
cat("Number of Female observations:", female_count, "\n")
#Number of Male observations: 14 
#Number of Female observations: 14 
```


``` {r  C}
# Create a data frame with the provided data
data <- data.frame(
  Respondents = 1:10,
  Sex = c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male"),
  Fathers_Occupation = c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3),
  Person_at_Home = c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6),
  Siblings_at_school = c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2),
  Types_of_houses = c("Wood", "Concrete", "Concrete", "Wood", "Semi-Concrete", "Semi-Concrete", "Wood", "Semi-Concrete", "Semi-Concrete", "Concrete")
)

gender_counts <- table(data$Sex)


bar_colors <- c("red", "yellow")

barplot(gender_counts, main="Number of Males and Females", xlab="Sex", ylab="Count", col=bar_colors,
        legend.text=c("Male", "Female"), beside=TRUE)
legend("topright", legend=c("Male", "Female"), fill=bar_colors)

``` 

``` {r  num5}

expenses <- c(Food = 60, Electricity = 10, Savings = 5, Miscellaneous = 25)

pie(expenses, labels = paste(names(expenses), "(", round((expenses/sum(expenses))*100), "%)"), 
    col = c("green", "yellow", "purple", "orange"),
    main = "Monthly Expenses of Dela Cruz Family")

legend("topright", legend = names(expenses), fill = c("green", "yellow", "purple", "orange"))

```

```{r num6 A}
data(iris)
str(iris)
```

```{r num6 B}
mean_values <- c(mean(iris$Sepal.Length),
mean(iris$Sepal.Width),
mean(iris$Petal.Length),
mean(iris$Petal.Width))
```

``` {r  num6C}
pie(table(iris$Species), labels = c("Setosa", "Versicolor", "Virginica"), col = c("green", "orange", "purple"), main = "Species Distribution")

```
```{r num6D}
setosa_data <- iris[iris$Species == "setosa", ]
versicolor_data <- iris[iris$Species == "versicolor", ]
virginica_data <- iris[iris$Species == "virginica", ]

head(setosa_data, 6)
head(versicolor_data, 6)
head(virginica_data, 6)

```
```{r num6E}
plot(x = iris$Sepal.Length[iris$Species == "setosa"], y = iris$Sepal.Width[iris$Species == "setosa"], pch = 16, col = "green", main = "Iris Dataset", xlab = "Sepal Length", ylab = "Sepal Width")
points(x = iris$Sepal.Length[iris$Species == "versicolor"], y = iris$Sepal.Width[iris$Species == "versicolor"], pch = 17, col = "orange")
points(x = iris$Sepal.Length[iris$Species == "virginica"], y = iris$Sepal.Width[iris$Species == "virginica"], pch = 18, col = "purple")

```
```{r num6F}
# The color green has the longest length and width which is the Setosa.
```

```{r num7}

my_data <- read_xlsx("alexa_file.xlsx")
my_data



```
```{r num7A}

```




