---
title: "RWorksheet-4a"
output: pdf_document
date: "2023-10-25"
---
#1
```{r num1a}
ShoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)

Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0)

Gender <- c("F", "F", "F", "F", "M", "F", "F", "F","M", "F", "M", "F", "M","M")

library("writexl")
df <- data.frame(ShoeSize, Height, Gender)
print(df)

write_xlsx(df, "C:\\Users\\Ron\\Desktop\\Test\\people.xlsx")
```

```{r num1b}
m_subset <- subset(df, Gender == "M", select = c("ShoeSize", "Gender"))
f_subset <- subset(df, Gender == "F", select = c("ShoeSize", "Gender"))

m_subset
f_subset
```

```{r num1c}
Shoesize <- mean(df$ShoeSize)
height <- mean(df$Height)
Shoesize
height
```

```{r num1d}
#Is a correlation between shoe size and height, it is not a strict one because these two factors are not interdependent
```
#2
```{r num2}
 months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")

factor_months <- factor(months)
print(factor_months)

```
#3
```{r num3}
   summary_months <- summary(months)
   summary_monthsVector <- summary(factor_months)
   
   summary_months
   summary_monthsVector
```

#4
```{r num4}

factor_data <- c("East", "West", "North")
frequency <- c(1,4,3)

new_order_data <- factor(factor_data,levels = c("East","West","North"))
new_order_data
```

```{num 5}
table <- read.table(file = "Import_March.csv", header = TRUE, sep = ',')
table

```
```{r num6}

random_number <- sample(1:50, 1)

cat("The chosen number is:", random_number, "\n")

if (random_number == 20) {
  cat("TRUE\n")
} else if (random_number < 1 || random_number > 50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else {
  cat(random_number, "\n")
}

```
```{r num7}

calculate_min_bills <- function(price_of_snack) {
  bill_denominations <- c(1000, 500, 200, 100, 50)
  total_bills <- 0
  
  for (bill in bill_denominations) {
    num_bills_needed <- price_of_snack %/% bill
    price_of_snack <- price_of_snack %% bill
    total_bills <- total_bills + num_bills_needed
  }
  
  cat("Minimum number of bills needed to purchase the snack:", total_bills, "\n")
}

price_of_snack <- 2800
calculate_min_bills(price_of_snack)

```
```{r num8A}
#A

students <- data.frame(
  Name = c("Annie" , "Thea", "Steve", "Hanna"),
  Grade1 = c(85,65,75,95),
  Grade2 = c(65,75,55,75),
  Grade3 = c(85,90,80,100),
  Grade4 = c(100,90,85,90)
)
students
```
```{r num8B}
#B
students$Average <- (students$Grade1 + students$Grade2 + students$Grade3 + students$Grade4) / 4

for (i in 1:nrow(students)) {
  if (students$Average[i] > 90) {
    cat(students$Name[i], "'s average grade this semester is", students$Average[i], "\n")
  }
}

```
```{r num8C}
#C
test1_average <- sum(students$Grade1) / nrow(students)
test2_average <- sum(students$Grade2) / nrow(students)
test3_average <- sum(students$Grade3) / nrow(students)
test4_average <- sum(students$Grade4) / nrow(students)

if (test1_average < 80) {
  cat("The 1st test was difficult.\n")
}
if (test2_average < 80) {
  cat("The 2nd test was difficult.\n")
}
if (test3_average < 80) {
  cat("The 3rd test was difficult.\n")
}
if (test4_average < 80) {
  cat("The 4th test was difficult.\n")
}
```
```{r num8D}
#D
for (i in 1:nrow(students)) {
  highest_grade <- students$Grade1[i]
  if (students$Grade2[i] > highest_grade) {
    highest_grade <- students$Grade2[i]
  }
  if (students$Grade3[i] > highest_grade) {
    highest_grade <- students$Grade3[i]
  }
  if (students$Grade4[i] > highest_grade) {
    highest_grade <- students$Grade4[i]
  }
  if (highest_grade > 90) {
    cat(students$Name[i], "'s highest grade this semester is", highest_grade, "\n")
  }
}
```
















